name = "Nightmare Survival"
author = "MatiasVME"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "11e66170af55a43fbed8da8508446048735a91a93392be85231a11e4bc0b6a09"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"
